services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8036:8000"
    volumes:
      - /app
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/zombotopia.db
    networks:
      - zombotopia-network
    depends_on:
      - db

  db:
    image: keinos/sqlite3
    volumes:
      - sqlite_data:/data
    networks:
      - zombotopia-network

volumes:
  sqlite_data:

networks:
  zombotopia-network:
    driver: bridge