services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8036:8000"
    volumes:
      - /app
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/zombotopia.db
    depends_on:
      - db

  db:
    image: keinos/sqlite3
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: