name: Deploy to Server

on:
   push:
      branches: [ main ]

      jobs:
         deploy:
            runs-on: self-hosted

            steps:
               - name: Go to project directory
                 run: cd /home/sunrintoday/projects/zombotopia
               - name: Pull latest changes
                 run: git pull origin main
                              
               - name: Restart Docker containers
                 run: |
                   docker compose down api
                   docker compose up -d --build api
