name: Deploy to Server

on:
   push:
      branches: [ main ]

jobs:
   deploy:
      runs-on: self-hosted
      steps:
         - uses: actions/checkout@v3
         - name: Pull latest changes
           run: git pull origin main
                        
         - name: Restart Docker containers
           run: |
             docker compose down api
             docker compose up -d --build api
