name: Deploy to Server

on:
   push:
      branches: [ main ]

jobs:
   deploy:
      runs-on: self-hosted
      steps:
         - uses: actions/checkout@v3
         - name: Restart Docker containers
           run: |
             docker compose down
             docker compose up -d --build